github:
  token: "..."

kaggle:
  username: "..."
  key: "..."

opendatalab:
  username: "..."
  password: "..."

weights:
  "dinov3_vits16":
  "dinov3_vits16plus":
  "dinov3_vitb16": 
  "dinov3_vitl16": 
